version: 2.1


#test
executors:
  base-exec:
    docker:
      - image: 'cimg/base:stable'
jobs:
  test:
    executor: base-exec
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:nTn/dmOc5fORPLhqLAYxQUFB+94WN172pnNQ36tV2qw"
      - run: git clone -b "$CIRCLE_BRANCH" << pipeline.trigger_parameters.github_app.repo_url >>
            

orbs:
  node: circleci/node@3.0.0

workflows:
  my_workflow:
    jobs:       
      - test   

            #testing this out
            
