version: 2.1

orbs:
  macos: circleci/macos@2.4.1
  
jobs:
  build:
    macos:
      xcode: 15.0.0
    resource_class: macos.x86.medium.gen2
    
    steps:
      - run: echo "hello world! -- build job" 
  test:
    macos:
      xcode: 15.0.0
    resource_class: macos.x86.medium.gen2
    
    steps:
      - run: echo "ello! - test job"       
      
    
      
workflows:
  say-hello-workflow:
    jobs:
      - test
      - build: 
          filters:
            tags:
              only:
                - v2     

        
            
