version: 2.1

jobs:
  test-no-op:
    type: no-op
  test-unit:
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout


workflows:
  build-test-deploy:
    jobs:
      - test-no-op: 
          type: approval
      - test-unit

      #test
