version: 2.1

jobs:
  test-coordinator:
    type: no-op
  test-unit:
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout


workflows:
  build-test-deploy:
    jobs:
      - test-coordinator: 
          type: approval
      - test-unit

