version: 2.1

executors:
  base-exec:
    docker:
      - image: 'cimg/base:stable'
jobs:
  test:
    executor: base-exec
    steps:
      - run: - run: git clone -b "$CIRCLE_BRANCH" << pipeline.trigger_parameters.github_app.repo_url >>"

orbs:
  node: circleci/node@3.0.0

workflows:
  my_workflow:
    jobs:       
      - test   

            #testing this out
            
